#!/usr/bin/env bash
# Regenerates cowork/instructions.md from the canonical sources:
#   - AGENTS.md (the workflow contract)
#   - agents/*.md (role descriptions)
#   - skills/*/SKILL.md (skill triggers)
#
# Run this whenever any of those change. Re-paste the resulting file into
# the Claude CoWork project's Instructions / System Prompt field.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="${repo_root}/cowork/instructions.md"

cd "${repo_root}"

# Header / preamble — the bits CoWork specifically needs and the Claude Code
# surface doesn't (role announcement, no-hooks caveat, paste instructions).
cat > "${out}" <<'PREAMBLE'
# Gaia — Claude CoWork project instructions

> **Generated by `cowork/build.sh` from `AGENTS.md`, `agents/*.md`, and
> `skills/*/SKILL.md`. Do not edit by hand — re-run the build script.**
>
> Paste the contents of this file into your Claude CoWork project's
> "Instructions" / "System Prompt" / "Project Context" field. Pair it with
> the `gaia-remote` MCP connector (see `cowork/connector.json`).
> CoWork does not auto-discover Claude Code agents, skills, or slash
> commands; this single document substitutes for all of them.

---

You are operating as **Gaia** — a virtual team of AI roles that build and
evolve software using spec-driven development. You coordinate intake,
architecture, planning, engineering, testing, and release across one repo
without dropping QA, drift detection, or proof obligations.

## Output format

You play exactly one role at a time. Open every reply with the active role
on its own line, then deliver that role's expected output, then hand off
explicitly:

```
[role: solutions-architect]

... role output ...

> Handoff to: implementation-planner
> Reason: architecture is current; delivery needs sequencing.
```

Switch roles only when the current role's deliverable is complete.

PREAMBLE

# Embed the workflow contract verbatim.
{
    echo "## Workflow contract (verbatim from AGENTS.md)"
    echo
    sed 's/^# Gaia: Agent Constitution.*$/<!-- AGENTS.md -->/' AGENTS.md
    echo
} >> "${out}"

# Embed each role's frontmatter description.
{
    echo "## Roles"
    echo
    echo "Each role below is a Claude Code agent in the source repo;"
    echo "in CoWork they map to the \`[role: ...]\` header you announce."
    echo
    for f in agents/*.md; do
        name="$(awk '/^name:/{print $2; exit}' "$f")"
        echo "### ${name}"
        echo
        # Extract the description block from the frontmatter (handles `>-` folded form).
        awk '
            /^---$/ { fm++; next }
            fm == 1 && /^description:/ { in_desc=1; sub(/^description:[ \t]*/,""); if ($0 != ">-" && $0 != ">") print $0; next }
            fm == 1 && in_desc && /^[a-zA-Z][a-zA-Z0-9_-]*:/ { in_desc=0 }
            fm == 1 && in_desc { sub(/^[ \t]+/,""); print }
        ' "$f"
        echo
    done
} >> "${out}"

# Embed each skill's description so the model knows when to apply each one.
{
    echo "## Skills (when to apply)"
    echo
    echo "These are Claude Code skills in the source repo. CoWork has no"
    echo "auto-discovery, so use the description as a trigger: when the"
    echo "described situation arises, apply the skill's guidance."
    echo
    for f in skills/*/SKILL.md; do
        name="$(awk '/^name:/{print $2; exit}' "$f")"
        desc="$(awk '/^description:/{sub(/^description:[ \t]*/,""); print; exit}' "$f")"
        echo "- **${name}**: ${desc}"
    done
    echo
} >> "${out}"

# Closing operating rhythm + DOD.
cat >> "${out}" <<'CLOSING'
## Operating rhythm

- **Every session start**: produce a Repo Survey, then call
  `memory_recall(project)` and `evolve_list()` to load context.
- **Drift detected**: stop feature work, fix drift, then resume.
- **After mistakes/inefficiencies**: `evolve_log` to capture the lesson.
- **After applying a lesson**: `evolve_apply` to close the loop.
- **Need human input**: `tasks_request_input` and continue with parallel
  work that doesn't depend on the answer.
- **No "TODO left behind"**: every TODO becomes an MCP task or a blocker
  on an existing one.

## What CoWork specifically can't do

- No slash commands. Treat `/gaia-init`, `/gaia-intake`, `/gaia-plan`,
  `/gaia-review`, `/gaia-evolve` as plain-English requests for the
  matching role.
- No hooks. The Claude Code `SessionStart` / `PreToolUse` policy scripts
  do not run here; honor the same policies manually.
- No subagent isolation. Switch role via the `[role: ...]` header in a
  single conversation instead of spawning fresh contexts.
CLOSING

echo "Wrote ${out}"
echo "Re-paste this file into your Claude CoWork project's Instructions field."
